USE [CS_WMS]
GO

/****** Object:  StoredProcedure [dbo].[CS_SP_WMS_USER_MENU_PRODUCT]    Script Date: 7/3/2018 2:33:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


create PROCEDURE [dbo].[CS_SP_WMS_USER_MENU_PRODUCT]
@UserID NVARCHAR(255)='',
@Password NVARCHAR(255)='',
@ProductAsk NVARCHAR(255)
AS	
DECLARE @ProdAsk bigint =0
BEGIN
SET @ProdAsk = DBO.[GetProductAsk]  (@UserID ,@Password,CAST(@ProductAsk AS bigint));

IF(@ProdAsk <> 0)
BEGIN
SELECT SYS_MENU.*
FROM SYS_MENUGROUP_USER_JUN
INNER JOIN SYS_USER ON SYS_USER.Ask = SYS_MENUGROUP_USER_JUN.[User]
INNER JOIN SYS_MENUGROUP_JUN ON SYS_MENUGROUP_JUN.[Menu Group] =   SYS_MENUGROUP_USER_JUN.[Menu Group]
INNER JOIN SYS_MENUGROUP ON SYS_MENUGROUP.Ask  = SYS_MENUGROUP_JUN.[Menu Group]
INNER JOIN SYS_MENU ON SYS_MENU.Ask = SYS_MENUGROUP_JUN.MENU
INNER JOIN SYS_PRODUCT_USER_JUN ON SYS_PRODUCT_USER_JUN.[USER] = SYS_USER.Ask
WHERE SYS_USER.[User ID]=CAST(@UserID AS NVARCHAR(255)) AND SYS_Menu.[Menu Type] = 2
AND SYS_PRODUCT_USER_JUN.PRODUCT = @ProdAsk
ORDER BY SYS_USER.[User ID],SYS_MENU.[Menu Tab],SYS_MENU.[Menu Pannel],SYS_MENU.[Menu Name]

END
 
END

GO


